<script setup lang="ts">
/**
 * Dashboard home (Balance) — V2 Phase 2.
 *
 * Every figure on this page is real: wallet balance, active count and project
 * rows from /api/dashboard/stats, the credit line from the CreditLine record on
 * that same payload, and the expense breakdown from the installment plans on
 * /api/orders. The only decoration left is the promo's growth card, which is
 * labelled as an example so it cannot be read as this account's own figure.
 */
definePageMeta({
  title: 'Dashboard',
  layout: 'sidenav',
  middleware: 'auth',
})

const { user } = useUser()
const { formatCurrency } = useCurrency()

const showPromo = ref(true)
const howOpen = ref(false)

const { data } = await useFetch('/api/dashboard/stats')

const firstName = computed(() =>
  user.value?.firstName || (user.value?.email ? user.value.email.split('@')[0] : 'there'),
)

const stats = computed(() => data.value?.stats ?? { activeProjects: 0, walletBalance: 0, adCredits: 0, totalSpent: 0 })
const projects = computed(() => data.value?.projects ?? [])

/**
 * Credit line — the real `CreditLine` record, not a quoted figure.
 *
 * This card used to hard-code a £12,500 limit and a green "Approved" chip in
 * the front end. That is a credit facility with terms, generated by a template:
 * it has to come from the record or not be shown at all. The record is `null`
 * until the customer applies, so the card has four honest states instead of
 * one fabricated one.
 */
const creditLine = computed<any>(() => (data.value as any)?.credit ?? null)
const credit = computed(() => {
  const line = creditLine.value
  const limit = line?.limit ?? 0
  const used = line?.used ?? 0
  return {
    status: (line?.status ?? 'NONE') as 'NONE' | 'PENDING' | 'ACTIVE' | 'FROZEN' | 'REJECTED',
    limit,
    used,
    available: Math.max(0, limit - used),
    // Clamped: an over-limit account (used > limit, which the ledger does
    // allow) would otherwise ask the bar to draw past its own track.
    pct: limit > 0 ? Math.min(100, Math.round((used / limit) * 100)) : 0,
  }
})

// Service catalogue — "from £X/mo" prices come from /api/config
// (Setting catalog.from-prices, admin-editable); card chrome stays local.
const { data: appConfig } = await useFetch('/api/config', { lazy: true })

/**
 * One badge, on the one service we actually want to push. Badging all four
 * (HOT / NEW / POPULAR / POPULAR) cancelled them out and left two things on
 * the page competing with the promo CTA.
 */
const SERVICE_CARDS = [
  { key: 'marketing', name: 'Digital marketing', desc: 'Zero upfront cost · ROI-focused campaigns', fallback: 290, icon: 'lucide:megaphone', badge: 'Most popular' },
  { key: 'development', name: 'Web development', desc: 'Modern stack · high-performance builds', fallback: 420, icon: 'lucide:code-2', badge: '' },
  { key: 'seo', name: 'SEO optimisation', desc: 'Rank #1 on Google Search', fallback: 190, icon: 'lucide:search', badge: '' },
  { key: 'branding', name: 'Branding & design', desc: 'Logo, UI/UX and visual identity', fallback: 250, icon: 'lucide:palette', badge: '' },
]
const services = computed(() => SERVICE_CARDS.map(card => ({
  ...card,
  from: (appConfig.value as any)?.fromPrices?.[card.key] ?? card.fallback,
})))

/**
 * Expenses — the total and its parts, or the total alone. Never both sources.
 *
 * This card used to contradict itself on screen: the headline rendered the
 * API's real `totalSpent` while the breakdown beside it rendered a hardcoded
 * £3,200 / £3,100 / £1,940 array. A customer who spots a total that disagrees
 * with its own parts stops trusting every other number in the panel.
 *
 * `Transaction` is the money-truth and gives the headline. Per-project
 * attribution only exists on the installment plans, and `installmentPlan.paid`
 * is a counter that is not guaranteed to be ledger-backed — seeded or
 * adjusted plans can carry a `paid` value with no matching transaction. So the
 * breakdown is rendered only when the plans provably add up to the ledger
 * total; otherwise the card shows the honest total on its own.
 *
 * TODO(api): a ledger-derived per-project figure on /api/dashboard/stats
 * (sum of `Transaction` rows grouped by the owning project) would let the
 * breakdown render unconditionally and retire this reconciliation guard.
 */
const { data: ordersData } = await useFetch('/api/orders', { lazy: true })

const EXPENSE_TONES = ['bg-primary-500', 'bg-primary-400', 'bg-primary-300', 'bg-primary-200', 'bg-primary-100']

interface ExpenseRow { label: string, value: number, months: number, class: string }

// Paid-to-date per project, biggest first. Candidate parts, not yet trusted.
const planRows = computed(() =>
  ((ordersData.value as any)?.data ?? [])
    .map((project: any) => ({
      label: project.name as string,
      value: (project.installmentPlan?.paid ?? 0) as number,
      months: (project.installmentPlan?.monthsPaid ?? 0) as number,
    }))
    .filter((row: any) => row.value > 0)
    .sort((a: any, b: any) => b.value - a.value) as Omit<ExpenseRow, 'class'>[],
)

const expenseTotal = computed(() => stats.value.totalSpent)
const planTotal = computed(() => planRows.value.reduce((sum, row) => sum + row.value, 0))

// Sub-penny tolerance: these are floats that have been through monthly division.
const partsReconcile = computed(() =>
  planRows.value.length > 0 && Math.abs(planTotal.value - expenseTotal.value) < 0.01,
)

const expenses = computed<ExpenseRow[]>(() =>
  partsReconcile.value
    ? planRows.value.map((row, index) => ({ ...row, class: EXPENSE_TONES[index % EXPENSE_TONES.length]! }))
    : [],
)

function plural(count: number, word: string) {
  return `${count} ${word}${count === 1 ? '' : 's'}`
}

const expenseCaption = computed(() => {
  if (!expenses.value.length) {
    return 'Everything you have paid through Apex so far'
  }
  const months = planRows.value.reduce((sum, row) => sum + row.months, 0)
  return `${plural(months, 'installment')} across ${plural(expenses.value.length, 'project')}`
})

const expenseLegend = computed(() =>
  expenses.value.map(row => `${formatCurrency(row.value)} ${row.label}`).join(', '),
)

/**
 * The plan's terms, shown as chips below `lg` in place of the growth card.
 *
 * All three are commitments the product actually makes (REQUIREMENTS §2), not
 * marketing adjectives — which is why they read as facts and why the 12-month
 * figure matches the financing maths in `services.vue` (ADR-011).
 */
const PROMO_FACTS = ['0% interest', '12 months', 'No credit check']

const HOW_STEPS = [
  { n: '1', title: 'Apply in two minutes', body: 'No credit card, no paperwork. We review your account, not your credit file.' },
  { n: '2', title: 'We start the work', body: 'Your campaign or build begins immediately, with nothing paid up front.' },
  { n: '3', title: 'Pay from the return', body: 'Repayments start once results land, spread over 12 months at 0%.' },
]

function statusMeta(status: string) {
  switch (status) {
    case 'In Progress':
      return { label: 'In progress', text: 'text-[#22B07D]', chip: 'bg-[#22B07D]/15', bar: 'bg-[#22B07D]' }
    case 'Completed':
      return { label: 'Completed', text: 'text-primary-400', chip: 'bg-primary-500/16', bar: 'bg-primary-500' }
    case 'Pending':
      return { label: 'Pending', text: 'text-[#F2C14E]', chip: 'bg-[#D9A521]/14', bar: 'bg-[#F2C14E]' }
    default:
      return { label: 'Started', text: 'text-primary-400', chip: 'bg-primary-500/16', bar: 'bg-primary-500' }
  }
}

const VIOLET_BLOB = 'radial-gradient(circle at 50% 38%, #9b79f6 0%, #7d53f2 55%, #6c40e8 100%)'
</script>

<template>
  <div class="mx-auto flex max-w-[1180px] flex-col gap-7 pb-8 font-sans text-muted-400 md:gap-8">
    <!--
      No header action: the cash card below already links to the wallet twice
      (Deposit funds, Transactions), and three routes to one page in a single
      viewport is noise rather than convenience.
    -->
    <ApexPageHeader subtitle="Manage your projects, wallet and services — all in one place.">
      <template #title>
        Welcome back, <span class="text-primary-400">{{ firstName }}</span>
      </template>
    </ApexPageHeader>

    <!-- ========== PROMO HERO ========== -->
    <Transition
      enter-active-class="transition-all duration-300 ease-out" enter-from-class="opacity-0 -translate-y-2"
      leave-active-class="transition-all duration-300 ease-in" leave-to-class="opacity-0 -translate-y-2"
    >
      <section
        v-if="showPromo"
        aria-label="Offer"
        class="order-3 relative overflow-hidden rounded-2xl border border-white/10 p-5 md:order-none md:p-[26px] lg:p-9"
        style="background: radial-gradient(110% 130% at 84% 16%, rgba(125,83,242,.24) 0%, rgba(125,83,242,0) 52%), linear-gradient(150deg, #16252A 0%, #101D21 62%, #0E181B 100%);"
      >
        <!--
          One blurred blob over the radial wash. The dotted mask texture that
          used to sit on top of both is gone — three stacked effects is what
          made this block read as heavier than everything below it.
        -->
        <div class="pointer-events-none absolute -top-16 right-28 size-72 rounded-full opacity-45 blur-[70px]" :style="{ background: VIOLET_BLOB }" />

        <button
          type="button" aria-label="Dismiss offer"
          class="apex-focus absolute right-3 top-3 z-10 flex size-11 items-center justify-center rounded-xl border border-white/10 bg-white/5 text-muted-400 transition hover:bg-white/10 hover:text-white sm:right-4 sm:top-4 sm:size-9"
          @click="showPromo = false"
        >
          <Icon name="lucide:x" class="size-4" />
        </button>

        <div class="relative z-[2] grid grid-cols-1 items-center gap-8 lg:grid-cols-[1.15fr_0.85fr]">
          <div>
            <!-- One chip. Emoji are a marketing-eyebrow accent, never product UI. -->
            <div class="mb-[18px] flex flex-wrap gap-2.5">
              <span class="inline-flex items-center rounded-full border border-warning-500/30 bg-warning-500/[0.13] px-3.5 py-1.5 text-[11.5px] font-bold uppercase tracking-[0.04em] text-warning-400">
                Limited spots this month
              </span>
            </div>
            <h2 class="font-heading text-[25px] font-extrabold leading-[1.05] tracking-[-0.025em] text-white sm:text-[40px]">
              Scale your business,<br>
              <span class="text-primary-400">pay from profits.</span>
            </h2>
            <p class="mb-[18px] mt-3 max-w-[520px] text-[14.5px] leading-[1.55] text-muted-400 sm:mb-6 sm:mt-[18px] sm:text-[15.5px]">
              Don't let cash flow stop your growth. Use our <strong class="font-semibold text-white">Zero Upfront Payment</strong> plan for Digital Marketing &amp; SEO services. We invest in you, you split the win.
            </p>
            <!--
              The plan's three terms, as chips, below `lg` — exactly where the
              growth card is hidden. They are claims the product actually makes
              (REQUIREMENTS §2: 0% over twelve months, no credit check), not
              decoration, so they carry a tick rather than a colour.
            -->
            <div class="mb-[18px] flex flex-wrap gap-2 lg:hidden">
              <span
                v-for="fact in PROMO_FACTS" :key="fact"
                class="inline-flex items-center gap-[7px] rounded-full border border-white/10 bg-white/5 px-3 py-[7px] text-[12.5px] font-semibold text-white"
              >
                <Icon name="lucide:check" class="size-3.5 text-[#22B07D]" />{{ fact }}
              </span>
            </div>

            <!--
              Stacked and full width on a phone, side by side from `sm`: at
              393px two pills on one row leave each about 150px, and the
              secondary one wraps its own label.
            -->
            <div class="flex flex-col gap-2.5 sm:flex-row sm:flex-wrap sm:items-center sm:gap-4">
              <BaseButton to="/dashboards/services" rounded="full" variant="primary" class="h-[50px]! w-full px-6 shadow-[0_12px_28px_rgba(125,83,242,.32)] sm:h-12! sm:w-auto">
                <span>Get started now</span>
                <Icon name="lucide:arrow-right" class="size-4" />
              </BaseButton>
              <!--
                This used to call comingSoon(), which answered an informational
                question with "your account manager has been notified and will
                be in touch shortly". It now answers the question.
              -->
              <button
                type="button"
                class="apex-focus inline-flex h-12 w-full items-center justify-center gap-2.5 rounded-full border border-white/20 px-2 text-[14.5px] font-semibold text-white transition hover:text-primary-400 sm:w-auto sm:justify-start sm:border-0"
                :aria-expanded="howOpen"
                aria-controls="apex-how-it-works"
                @click="howOpen = !howOpen"
              >
                <span class="hidden size-[34px] items-center justify-center rounded-full border border-white/15 sm:inline-flex">
                  <Icon :name="howOpen ? 'lucide:chevron-up' : 'lucide:play'" class="size-3.5" />
                </span>
                How it works
                <Icon
                  name="lucide:chevron-down"
                  class="size-4 transition-transform duration-200 sm:hidden"
                  :class="howOpen ? 'rotate-180' : ''"
                />
              </button>
            </div>

            <div v-if="howOpen" id="apex-how-it-works" class="apex-fade mt-[22px] rounded-2xl border border-white/10 bg-muted-950/55 p-5">
              <div class="grid grid-cols-1 gap-4 sm:grid-cols-3 sm:gap-[18px]">
                <div v-for="step in HOW_STEPS" :key="step.n" class="flex items-start gap-3 sm:block">
                  <span class="inline-flex size-[26px] shrink-0 items-center justify-center rounded-full bg-primary-500/16 text-xs font-extrabold text-primary-400 sm:size-6">{{ step.n }}</span>
                  <div class="min-w-0 flex-1 sm:flex-none">
                    <div class="text-[13.5px] font-semibold text-white sm:mt-2.5">
                      {{ step.title }}
                    </div>
                    <div class="mt-1 text-[12.5px] leading-[1.5] text-muted-500">
                      {{ step.body }}
                    </div>
                  </div>
                </div>
              </div>
            </div>

            <p class="mt-5 text-xs text-muted-500">
              No credit card required for application.
            </p>
          </div>

          <!-- Illustrative growth card — labelled, so it cannot read as this account's own figure. -->
          <div class="hidden justify-center lg:flex">
            <div class="relative w-[290px]">
              <div class="-rotate-[4deg] rounded-2xl border border-white/15 p-6 shadow-[0_30px_60px_rgba(0,0,0,.4)] backdrop-blur" style="background: linear-gradient(160deg, rgba(30,47,53,.9), rgba(16,29,33,.9));">
                <div class="mb-3.5 flex items-center justify-between gap-2">
                  <span class="text-[11px] font-bold tracking-[0.06em] text-muted-500">REVENUE GROWTH</span>
                  <span class="inline-flex size-[30px] items-center justify-center rounded-full bg-[#22B07D]/16 text-[#22B07D]"><Icon name="lucide:trending-up" class="size-[15px]" /></span>
                </div>
                <div class="font-heading text-[38px] font-extrabold leading-none tracking-[-0.02em] text-white">
                  +145%
                </div>
                <div class="mt-[18px] flex h-[74px] items-end gap-2.5">
                  <div class="flex-1 rounded-[5px] bg-primary-500/35" style="height:38%" />
                  <div class="flex-1 rounded-[5px] bg-primary-500/45" style="height:52%" />
                  <div class="flex-1 rounded-[5px] bg-primary-500/40" style="height:44%" />
                  <div class="flex-1 rounded-[5px] bg-primary-500/60" style="height:70%" />
                  <div class="flex-1 rounded-[5px] bg-gradient-to-b from-primary-400 to-primary-600 shadow-[0_6px_16px_rgba(125,83,242,.5)]" style="height:100%" />
                </div>
                <div class="mt-4 text-[11px] font-semibold uppercase tracking-[0.06em] text-muted-500">
                  Example result
                </div>
              </div>
              <div class="apex-float absolute -bottom-5 -right-3.5 flex size-[58px] items-center justify-center rounded-2xl bg-gradient-to-br from-primary-400 to-primary-600 shadow-[0_16px_36px_rgba(125,83,242,.5)]">
                <Icon name="lucide:wand-sparkles" class="size-6 text-white" />
              </div>
            </div>
          </div>
        </div>
      </section>
    </Transition>

    <!-- ========== FINANCIAL STATUS ========== -->
    <!--
      Mobile reorders the page; desktop keeps the promo first, as designed.
      On a phone the promo is a full viewport of marketing before any of the
      customer's own data, so below `md` the order becomes greeting → cash
      balance → active work → promo → services → expenses. `order-*` does this
      without duplicating markup; `md:order-none` returns every section to its
      DOM position, which is the desktop order.
    -->
    <section class="order-1 flex flex-col gap-4 md:order-none">
      <ApexSectionLabel label="Financial status" />

      <div class="grid grid-cols-1 items-stretch gap-5 lg:grid-cols-[1fr_1.32fr]">
        <!-- cash balance (emphasised) -->
        <div class="relative flex flex-col overflow-hidden rounded-2xl border border-primary-500/30 p-5 md:p-6" style="background: linear-gradient(150deg, #241846, #16252A 72%);">
          <div class="pointer-events-none absolute -top-12 -right-6 size-40 rounded-full opacity-50 blur-[50px]" :style="{ background: VIOLET_BLOB }" />
          <div class="relative mb-5 flex items-center gap-3">
            <span class="flex size-9 items-center justify-center rounded-xl bg-white/10 text-white"><Icon name="lucide:wallet" class="size-[18px]" /></span>
            <span class="text-xs font-bold uppercase tracking-[0.06em] text-primary-200">Cash balance</span>
          </div>
          <div class="relative flex items-baseline gap-2">
            <!-- 36px on a phone: the mobile type scale caps the money display
                 at 36px, and £-thousands wrap the 44px size at 393px. -->
            <span class="font-heading text-[32px] font-extrabold leading-none tracking-[-0.02em] text-white tabular-nums sm:text-[44px]">{{ formatCurrency(stats.walletBalance) }}</span>
          </div>
          <div class="relative mt-2.5 text-[13.5px] text-muted-400">
            Available to spend right now
          </div>
          <div class="relative mt-auto flex flex-wrap items-center gap-3.5 pt-6">
            <BaseButton rounded="full" to="/dashboards/wallet" class="h-11! px-5 !bg-white !text-muted-900 hover:!bg-primary-50">
              <Icon name="lucide:plus" class="size-4" /> Deposit funds
            </BaseButton>
            <NuxtLink to="/dashboards/wallet" class="apex-focus inline-flex items-center gap-1.5 rounded-md text-[13.5px] font-semibold text-primary-200 transition hover:text-white">
              Transactions <Icon name="lucide:arrow-right" class="size-3.5" />
            </NuxtLink>
          </div>
        </div>

        <!-- credit line — real CreditLine record, four states -->
        <div class="flex flex-col rounded-2xl border border-white/10 bg-muted-800 p-5 transition hover:border-white/15 md:p-6">
          <div class="mb-5 flex items-center justify-between gap-3">
            <span class="inline-flex items-center gap-3 text-xs font-bold uppercase tracking-[0.06em] text-muted-500">
              <span class="flex size-9 items-center justify-center rounded-xl bg-[#22B07D]/14 text-[#22B07D]"><Icon name="lucide:credit-card" class="size-[18px]" /></span>Credit line
            </span>
            <span v-if="credit.status === 'ACTIVE'" class="inline-flex shrink-0 items-center gap-1.5 rounded-full bg-[#22B07D]/14 px-2.5 py-1 text-[11px] font-bold text-[#22B07D]"><Icon name="lucide:check" class="size-3" />Approved</span>
            <span v-else-if="credit.status === 'PENDING'" class="inline-flex shrink-0 items-center gap-1.5 rounded-full bg-[#D9A521]/14 px-2.5 py-1 text-[11px] font-bold text-[#F2C14E]"><Icon name="lucide:clock" class="size-3" />Under review</span>
            <span v-else-if="credit.status === 'FROZEN'" class="inline-flex shrink-0 items-center gap-1.5 rounded-full bg-[#EC6453]/16 px-2.5 py-1 text-[11px] font-bold text-[#EC6453]"><Icon name="lucide:pause" class="size-3" />On hold</span>
          </div>

          <template v-if="credit.status === 'ACTIVE' || credit.status === 'FROZEN'">
            <div class="flex flex-wrap items-baseline gap-2">
              <span class="font-heading text-[32px] font-extrabold leading-none tracking-[-0.02em] text-white tabular-nums sm:text-[40px]">{{ formatCurrency(credit.available) }}</span>
              <span class="text-sm font-semibold text-muted-400">remaining</span>
              <span class="ml-auto text-[13.5px] text-muted-500">of <span class="font-semibold text-white tabular-nums">{{ formatCurrency(credit.limit) }}</span> limit</span>
            </div>
            <div role="progressbar" :aria-valuenow="credit.used" aria-valuemin="0" :aria-valuemax="credit.limit" class="my-[18px] h-2.5 overflow-hidden rounded-full bg-white/5">
              <div class="h-full rounded-full bg-gradient-to-r from-primary-400 to-primary-500" :style="{ width: `${credit.pct}%` }" />
            </div>
            <!--
              One labelled row each below `sm`, with the figure pushed right in
              tabular numerals so the two amounts line up under one another.
              Side by side they collided at 393px: two labels and two
              currency values on one 12.5px line had nowhere to wrap.
            -->
            <div class="flex flex-col gap-2 text-[13px] sm:flex-row sm:flex-wrap sm:items-center sm:justify-between sm:gap-2 sm:text-[12.5px]">
              <span class="flex items-center gap-2 text-muted-400 sm:inline-flex sm:gap-1.5"><span class="size-2 shrink-0 rounded-full bg-primary-500" />Used <strong class="ml-auto font-semibold text-white tabular-nums sm:ml-0">{{ formatCurrency(credit.used) }}</strong></span>
              <span class="flex items-center gap-2 text-muted-400 sm:inline-flex sm:gap-1.5"><span class="size-2 shrink-0 rounded-full border border-white/15 bg-white/5" />Available <strong class="ml-auto font-semibold text-white tabular-nums sm:ml-0">{{ formatCurrency(credit.available) }}</strong></span>
            </div>
            <div class="mt-auto flex items-center gap-2 border-t border-white/10 pt-[18px] text-[13px] text-muted-400">
              <Icon :name="credit.status === 'FROZEN' ? 'lucide:info' : 'lucide:shield-check'" class="size-[15px] shrink-0" :class="credit.status === 'FROZEN' ? 'text-[#EC6453]' : 'text-[#22B07D]'" />
              {{ credit.status === 'FROZEN' ? 'Your credit is on hold. Contact support to restore access.' : 'Interest-free while your installment plan is on schedule.' }}
            </div>
          </template>

          <template v-else-if="credit.status === 'PENDING'">
            <div class="font-heading text-[26px] font-extrabold leading-tight tracking-[-0.02em] text-white">
              Application received
            </div>
            <p class="mt-2 max-w-[380px] text-[13.5px] leading-[1.5] text-muted-400">
              We are reviewing your account. You will get a notification here as soon as there is a decision — usually within one working day.
            </p>
            <div class="mt-auto flex items-center gap-2 border-t border-white/10 pt-[18px] text-[13px] text-muted-400">
              <Icon name="lucide:clock" class="size-[15px] shrink-0 text-[#F2C14E]" />No action needed from you.
            </div>
          </template>

          <template v-else>
            <div class="font-heading text-[26px] font-extrabold leading-tight tracking-[-0.02em] text-white">
              Spread the cost, at 0%
            </div>
            <p class="mt-2 max-w-[380px] text-[13.5px] leading-[1.5] text-muted-400">
              Apply for an Apex credit line and pay for projects over 12 months with no interest and nothing up front.
            </p>
            <div class="mt-auto flex flex-wrap items-center gap-3 pt-[18px]">
              <BaseButton to="/dashboards/wallet" rounded="full" variant="primary" class="h-11! px-5">
                Apply for credit
              </BaseButton>
              <span class="text-[12.5px] text-muted-500">No credit check</span>
            </div>
          </template>
        </div>
      </div>
    </section>

    <!-- ========== ACTIVE WORK ========== -->
    <section class="order-2 flex flex-col gap-4 md:order-none">
      <div class="flex flex-wrap items-center justify-between gap-4">
        <div class="flex flex-wrap items-center gap-3.5">
          <ApexSectionLabel label="Active work" />
          <!-- Just the count on a phone: "Active work" already says what is being counted. -->
          <span class="rounded-full border border-white/10 bg-white/5 px-3 py-1 text-[12.5px] font-semibold text-white tabular-nums">
            <span class="sm:hidden">{{ stats.activeProjects }}</span>
            <span class="hidden sm:inline">{{ plural(stats.activeProjects, 'project') }}</span>
          </span>
        </div>
        <NuxtLink to="/dashboards/orders" aria-label="View all projects" class="apex-focus inline-flex min-h-11 items-center gap-1.5 rounded-md text-[13.5px] font-semibold text-primary-400 transition hover:text-white sm:min-h-0">
          <span class="sm:hidden">All</span><span class="hidden sm:inline">View all projects</span>
          <Icon name="lucide:arrow-right" class="size-3.5" />
        </NuxtLink>
      </div>

      <div v-if="projects.length" role="list" class="overflow-hidden rounded-2xl border border-white/10 bg-white/[0.02]">
        <template v-for="(project, idx) in projects" :key="project.id">
          <div v-if="idx > 0" class="h-px bg-white/10" />
          <!--
            Status is shown once, by the chip. The row used to also carry a
            coloured left border on top of the coloured progress bar — three
            encodings of the same fact, which is what made the list feel busy.
          -->
          <!--
            Two lines on a phone, one from `sm`: identity and status first, then
            progress, percentage and deadline. Squeezing all five onto one line
            at 393px is why the bar and the deadline used to be hidden below
            `sm` and `md` — which left a phone with no progress on screen at
            all, on the section whose whole job is progress.

            `sm:contents` dissolves the two line wrappers on wider screens so
            their children become direct flex items of the row again; the chip
            takes `sm:order-last` to land back at the end, where it was.
          -->
          <NuxtLink
            to="/dashboards/orders" role="listitem"
            class="flex flex-col gap-3 px-4 py-[14px] transition hover:bg-white/[0.03] sm:flex-row sm:items-center sm:gap-4 sm:px-[22px] sm:py-[18px]"
          >
            <div class="flex items-center gap-3 sm:contents">
              <span class="flex size-10 shrink-0 items-center justify-center rounded-xl border border-white/10 bg-white/5 text-muted-400 sm:size-[42px]"><Icon :name="project.icon" class="size-[19px]" /></span>
              <div class="min-w-0 flex-1">
                <div class="truncate text-[15px] font-semibold text-white">
                  {{ project.name }}
                </div>
                <div class="mt-0.5 truncate text-[12.5px] text-muted-500 sm:text-[13px]">
                  {{ project.category }}
                </div>
              </div>
              <span class="shrink-0 rounded-full px-3 py-1.5 text-center text-[11px] font-bold sm:order-last" :class="[statusMeta(project.status).chip, statusMeta(project.status).text]">{{ statusMeta(project.status).label }}</span>
            </div>

            <div class="flex items-center gap-2.5 sm:contents">
              <div class="flex min-w-0 flex-1 items-center gap-2.5 sm:w-[170px] sm:flex-none sm:shrink-0">
                <div class="h-1.5 flex-1 overflow-hidden rounded-full bg-white/5">
                  <div class="h-full rounded-full" :class="statusMeta(project.status).bar" :style="{ width: `${project.progress}%` }" />
                </div>
                <span class="w-[34px] shrink-0 text-right text-xs font-bold text-white tabular-nums">{{ project.progress }}%</span>
              </div>
              <!--
                Shown on a phone, where line two has the room, and from `md`,
                where the row does. Hidden only in the 640–767px band, which is
                the one width with neither — exactly as before this change.
              -->
              <span v-if="project.deadline" class="inline-flex shrink-0 items-center gap-1.5 text-[12px] text-muted-500 sm:hidden md:inline-flex md:w-24 md:text-[12.5px]"><Icon name="lucide:calendar" class="size-3.5" />{{ project.deadline }}</span>
            </div>
          </NuxtLink>
        </template>
      </div>

      <div v-else class="flex flex-col items-center justify-center rounded-2xl border border-dashed border-white/15 bg-white/[0.02] p-10 text-center">
        <span class="mb-4 flex size-14 items-center justify-center rounded-full bg-white/5 text-muted-500"><Icon name="lucide:folder-plus" class="size-7" /></span>
        <div class="text-base font-bold text-white">
          No active projects
        </div>
        <p class="mb-5 mt-1 max-w-[220px] text-[13px] text-muted-500">
          Start a new project to track its progress here.
        </p>
        <BaseButton to="/dashboards/services" rounded="full" variant="primary" class="h-11! px-5">
          <Icon name="lucide:plus" class="size-4" />Start a project
        </BaseButton>
      </div>
    </section>

    <!-- ========== ORDER A SERVICE ========== -->
    <section class="order-4 flex flex-col gap-4 md:order-none">
      <div class="flex flex-wrap items-end justify-between gap-4">
        <div>
          <ApexSectionLabel label="Order a service" class="mb-2" />
          <p class="text-sm text-muted-400">
            Pick a service to see pricing and monthly installments.
          </p>
        </div>
        <NuxtLink to="/dashboards/services" class="apex-focus inline-flex shrink-0 items-center gap-1.5 rounded-full border border-white/10 bg-muted-800 px-4 py-2.5 text-[13px] font-semibold text-white transition hover:border-white/15 hover:bg-muted-700">
          View full catalog <Icon name="lucide:arrow-right" class="size-3.5" />
        </NuxtLink>
      </div>

      <!--
        Four 20px-padded cards stacked is four screens of scrolling, so below
        `md` each becomes a 76px row: icon, name, one line of description, the
        from price, and a chevron doing the work the Order link did. Same link,
        same target, same accessible name — only the composition changes.
      -->
      <div class="grid grid-cols-1 gap-2.5 md:grid-cols-2 md:gap-5 lg:grid-cols-4">
        <NuxtLink
          v-for="svc in services" :key="svc.key"
          :to="`/dashboards/services?service=${svc.key}`"
          :aria-label="`Order ${svc.name} — from ${formatCurrency(svc.from)} per month`"
          class="apex-focus group relative flex min-h-[76px] flex-row items-center gap-3.5 rounded-2xl border border-white/10 bg-muted-800 px-4 py-3.5 transition duration-150 hover:border-primary-500/50 md:min-h-0 md:flex-col md:items-stretch md:gap-0 md:px-5 md:py-5 md:hover:-translate-y-[3px]"
        >
          <span class="flex size-11 shrink-0 items-center justify-center rounded-xl bg-primary-500/14 text-primary-400 md:mb-[18px]"><Icon :name="svc.icon" class="size-[21px]" /></span>
          <!--
            The badge sits beside the name on a row and at the top-right corner
            on a tile. Absolute positioning from `md` reproduces the tile
            exactly without a second copy of the element.
          -->
          <span
            v-if="svc.badge"
            class="order-2 shrink-0 whitespace-nowrap rounded-full bg-primary-500 px-2 py-[3px] text-[9.5px] font-extrabold uppercase tracking-[0.04em] text-white md:absolute md:right-5 md:top-5 md:px-2.5 md:py-1 md:text-[10.5px]"
          >{{ svc.badge }}</span>

          <div class="order-1 flex min-w-0 flex-1 flex-col md:order-none md:w-full">
            <div class="flex min-w-0 items-center gap-2">
              <span class="font-heading truncate text-base font-bold leading-[1.2] tracking-[-0.01em] text-white md:text-[18px] md:leading-normal">{{ svc.name }}</span>
            </div>
            <div class="mt-[3px] truncate text-[12.5px] leading-[1.4] text-muted-500 md:mt-1.5 md:whitespace-normal md:text-[13px] md:leading-[1.45]">
              {{ svc.desc }}
            </div>
            <!-- Price inline on a row; in the bordered footer on a tile. -->
            <div class="mt-[5px] text-[12.5px] leading-[1.3] text-muted-500 md:hidden">
              from <strong class="text-[13.5px] font-bold text-white tabular-nums">{{ formatCurrency(svc.from) }}</strong>/mo
            </div>
            <div class="mt-auto hidden items-center justify-between border-t border-white/10 pt-4 md:flex">
              <span class="text-[12.5px] text-muted-500">from <strong class="text-sm font-bold text-white tabular-nums">{{ formatCurrency(svc.from) }}</strong>/mo</span>
              <span class="inline-flex items-center gap-1.5 text-[13px] font-bold text-primary-400">Order <Icon name="lucide:arrow-right" class="size-3.5 transition-transform group-hover:translate-x-0.5" /></span>
            </div>
          </div>

          <Icon name="lucide:chevron-right" aria-hidden="true" class="order-3 size-4 shrink-0 text-muted-500 md:hidden" />
        </NuxtLink>
      </div>
    </section>

    <!-- ========== EXPENSES ========== -->
    <section class="order-5 flex flex-col gap-4 md:order-none">
      <ApexSectionLabel label="Expenses" />
      <!--
        Total, then the split bar, then one row per project. The two-column
        desktop split put the legend beside a 12px bar with nowhere to wrap,
        so below `lg` it reads straight down instead.
      -->
      <div
        class="grid grid-cols-1 items-center gap-5 rounded-2xl border border-white/10 bg-muted-800 p-5 md:p-6 lg:gap-8"
        :class="expenses.length ? 'lg:grid-cols-[minmax(200px,240px)_1fr]' : ''"
      >
        <div>
          <div class="text-[13px] font-medium text-muted-500">
            Paid so far
          </div>
          <div class="mt-1.5 font-heading text-[32px] font-extrabold leading-[1.1] tracking-[-0.02em] text-white tabular-nums sm:text-[38px]">
            {{ formatCurrency(expenseTotal) }}
          </div>
          <div class="mt-2 text-[12.5px] leading-[1.5] text-muted-500">
            {{ expenseCaption }}
          </div>
        </div>

        <!--
          Rendered only when there is something to break down. An empty half of
          the card beats a fabricated split — this is the one place on the page
          where a wrong number costs trust in every other number.
        -->
        <div v-if="expenses.length">
          <div role="img" :aria-label="`Spending by project: ${expenseLegend}`" class="flex h-3 gap-[3px] overflow-hidden rounded-full">
            <div v-for="e in expenses" :key="e.label" class="h-full" :class="e.class" :style="{ flexGrow: e.value }" />
          </div>
          <!--
            One row per project below `sm` — dot, name, amount, share — with
            the share in a fixed column so the percentages line up under one
            another. Stacking the label over the amount only works once there
            are three columns to stack into.
          -->
          <div class="mt-4 grid grid-cols-1 gap-3 sm:mt-[18px] sm:grid-cols-3 sm:gap-[18px]">
            <div v-for="e in expenses" :key="e.label" class="flex min-w-0 items-center gap-2.5 sm:flex-col sm:items-start sm:gap-1.5">
              <span class="inline-flex min-w-0 flex-1 items-center gap-2 text-[13.5px] text-muted-400 sm:flex-none sm:text-[13px]"><span class="size-[9px] shrink-0 rounded-[3px]" :class="e.class" /><span class="truncate">{{ e.label }}</span></span>
              <span class="font-heading shrink-0 text-base font-bold text-white tabular-nums sm:text-[18px]">{{ formatCurrency(e.value) }}</span>
              <span class="w-[34px] shrink-0 text-right font-sans text-xs font-medium text-muted-500 tabular-nums sm:hidden">{{ Math.round((e.value / expenseTotal) * 100) }}%</span>
              <span class="font-sans hidden text-xs font-medium text-muted-500 sm:inline">{{ Math.round((e.value / expenseTotal) * 100) }}%</span>
            </div>
          </div>
        </div>
      </div>
    </section>
  </div>
</template>

<style scoped>
@keyframes apex-float {
  0%,
  100% {
    transform: translateY(0);
  }
  50% {
    transform: translateY(-7px);
  }
}
.apex-float {
  animation: apex-float 5s cubic-bezier(0.65, 0, 0.35, 1) infinite;
}
@keyframes apex-fade {
  from {
    opacity: 0;
    transform: translateY(-4px);
  }
  to {
    opacity: 1;
    transform: translateY(0);
  }
}
.apex-fade {
  animation: apex-fade 0.2s ease-out both;
}
@media (prefers-reduced-motion: reduce) {
  .apex-float,
  .apex-fade {
    animation: none;
  }
}
</style>
